# Generated by Django 2.2.10 on 2020-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthletesScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название таблицы')),
                ('score_table', models.TextField(verbose_name='Таблица рекрдов')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
