# Generated by Django 2.2.10 on 2020-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesscore',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='athletesscore',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='scores/', verbose_name='Заставка'),
        ),
    ]
