# Generated by Django 2.2.10 on 2020-03-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('comp_type', models.CharField(max_length=80, verbose_name='Вид соревнований')),
                ('rank', models.PositiveIntegerField()),
                ('rank_code', models.CharField(max_length=4, verbose_name='Код страны')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('comp_date_start', models.DateField(verbose_name='Начало соревнований')),
                ('comp_date_end', models.DateField(verbose_name='Конец соревнований')),
                ('sponsor', models.CharField(max_length=200, verbose_name='Организатор')),
                ('participants', models.CharField(max_length=300, verbose_name='Участники')),
            ],
        ),
    ]
