# Generated by Django 2.2.10 on 2020-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionlist',
            name='description',
            field=models.CharField(default='Описание отсутствует', max_length=500, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='competitionlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
