# Generated by Django 2.2.10 on 2020-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20200322_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionlist',
            name='description',
            field=models.TextField(default='Описание отсутствует', max_length=500, verbose_name='Описание'),
        ),
    ]
