# Generated by Django 2.2.10 on 2020-02-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(db_index=True, max_length=400)),
                ('body', models.TextField(db_index=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
