# Generated by Django 2.2.10 on 2020-02-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0002_auto_20200224_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('img_object', models.ImageField(null=True, upload_to='images/test/')),
                ('related_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novatlet.Post')),
            ],
        ),
    ]
