# Generated by Django 2.2.10 on 2020-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0004_auto_20200225_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='test_location/photos/', verbose_name='Images'),
        ),
    ]
