# Generated by Django 2.2.10 on 2020-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0005_auto_20200228_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='dir_object',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Location'),
        ),
    ]
