# Generated by Django 2.2.10 on 2020-02-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0007_auto_20200228_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='images/test/', verbose_name='Images'),
        ),
    ]
