# Generated by Django 2.2.10 on 2020-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0008_auto_20200228_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='test_loclkdf/photos/', verbose_name='Images'),
        ),
    ]
