# Generated by Django 2.2.10 on 2020-02-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0009_auto_20200228_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='dir_object',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='fwfwdxewf/photos/', verbose_name='Images'),
        ),
    ]
