# Generated by Django 2.2.10 on 2020-02-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0010_auto_20200229_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='test_path/photos/', verbose_name='Images'),
        ),
    ]
