# Generated by Django 2.2.10 on 2020-02-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0011_auto_20200229_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='dir_object',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='weg/photos/', verbose_name='Images'),
        ),
    ]
