# Generated by Django 2.2.10 on 2020-03-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0013_auto_20200229_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='photos/', verbose_name='Images'),
        ),
    ]
