# Generated by Django 2.2.10 on 2020-03-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0014_auto_20200301_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='aaaaa/photos/', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='novatlet.Location'),
        ),
    ]
