# Generated by Django 2.2.10 on 2020-03-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0016_auto_20200301_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='dir_object',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='deafault_path/photos/', verbose_name='Images'),
        ),
    ]
