# Generated by Django 2.2.10 on 2020-03-01 20:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0018_auto_20200301_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='', verbose_name='Images'),
        ),
    ]
