# Generated by Django 2.2.10 on 2020-03-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0024_auto_20200302_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='boolean',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
