# Generated by Django 2.2.10 on 2020-03-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0025_auto_20200302_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='boolean',
        ),
        migrations.AlterField(
            model_name='photos',
            name='img_object',
            field=models.ImageField(db_index=True, upload_to='gallery/', verbose_name='Images'),
        ),
    ]
