# Generated by Django 2.2.10 on 2020-03-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0028_athlete_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='picture',
            field=models.ImageField(db_index=True, default='images/image.jpg', upload_to='images/athletes/'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='second_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
