# Generated by Django 2.2.10 on 2020-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novatlet', '0028_athlete_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athletes_awards',
            field=models.ManyToManyField(blank=True, related_name='athletesAw', to='novatlet.Award'),
        ),
    ]
