"""
Django settings for natlet project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')wfe0c!j6=^46cuxt$8%ch_oozt79ei6l)co*^bs#ja^@5#ajc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]']

#DEFAULT_FROM_EMAIL = 'parser9000@gmail.com'

#EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.beget.com'
EMAIL_HOST_USER = 'blog@palachintosh.com'
EMAIL_HOST_PASSWORD = 'ieb9b7&h'
EMAIL_PORT = 25



# Application definition

CKEDITOR_UPLOAD_PATH = "images/"
CKEDITOR_BASEPATH = "/static/www/ckeditor/ckeditor/"


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'novatlet',
    'contacts',
    'athletes',
    'competition',
    'comment',
    'ckeditor',
    'ckeditor_uploader',
    'ajax',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'natlet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        #'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'natlet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'atlet_site_db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# DATE_FORMAT = ['%d.%m.%Y']
DATE_FORMAT = 'd.m.Y'

DATETIME_FORMAT = 'd.m.Y H:i'

TIME_FORMAT = 'H:i'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'natlet/static/www/')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static/www')
STATIC_URL = '/static/www/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

GOOGLE_RECAPTCHA_KEY = '6Lf92-EUAAAAANywzHdBhjgQ3GrFf_apwe0ZDWqL'
GOOGLE_RECAPTCHA_SECRET_KEY = '6Lf92-EUAAAAABbiVG2vHe7NCzEgd_Co78cf-ppB'


#Content-Security-Policy directives

# CSP_DEFAULT_SRC = ("'none'", )
# CSP_STYLE_SRC = ("'self'", 'fonts.googleapis.com')
# # CSP_SCRIPT_SRC = ("'self'",
# #                   'unsafe-inline',
# #                   'https://code.jquery.com/', 
# #                   'https://*.google.com/',
# #                   'https://www.gstatic.com/',
# #                   'https://cdn.jsdelivr.net/',
# #                   'https://*.bootstrapcdn.com/',
# #                   )
CSP_SCRIPT_SRC = ("'none'")

try:
    from .local_settings import *
except ImportError:
    pass
